#!/bin/sh
set -eu

: "${PLANSCAPE_FRONTEND_BUCKET:?PLANSCAPE_FRONTEND_BUCKET is required}"

export PLANSCAPE_FRONTEND_BUCKET_PREFIX="${PLANSCAPE_FRONTEND_BUCKET_PREFIX:-}"
export PLANSCAPE_FRONTEND_ENVIRONMENT="${PLANSCAPE_FRONTEND_ENVIRONMENT:-production}"
export PLANSCAPE_FRONTEND_PRODUCTION="${PLANSCAPE_FRONTEND_PRODUCTION:-true}"
export PLANSCAPE_FRONTEND_IS_CATALOG_ENVIRONMENT="${PLANSCAPE_FRONTEND_IS_CATALOG_ENVIRONMENT:-false}"
export PLANSCAPE_FRONTEND_BACKEND_ENDPOINT="${PLANSCAPE_FRONTEND_BACKEND_ENDPOINT:-/planscape-backend}"
export PLANSCAPE_FRONTEND_DOWNLOAD_ENDPOINT="${PLANSCAPE_FRONTEND_DOWNLOAD_ENDPOINT:-}"
export PLANSCAPE_FRONTEND_MARTIN_SERVER="${PLANSCAPE_FRONTEND_MARTIN_SERVER:-/tiles/}"
export PLANSCAPE_FRONTEND_FEATURE_FLAGS="${PLANSCAPE_FRONTEND_FEATURE_FLAGS:-}"
export PLANSCAPE_FRONTEND_OPEN_PANEL_ENABLED="${PLANSCAPE_FRONTEND_OPEN_PANEL_ENABLED:-false}"
export PLANSCAPE_FRONTEND_MIXPANEL_ENABLED="${PLANSCAPE_FRONTEND_MIXPANEL_ENABLED:-false}"
export PLANSCAPE_FRONTEND_DEBUG_LAYERS="${PLANSCAPE_FRONTEND_DEBUG_LAYERS:-false}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_EXTRA_ERROR_DATA="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_EXTRA_ERROR_DATA:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_HTTPCLIENT="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_HTTPCLIENT:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_BROWSER_REPORTING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_BROWSER_REPORTING:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_INTERVENTIONS_REPORTING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_INTERVENTIONS_REPORTING:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_CRASH_REPORTING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_CRASH_REPORTING:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_PROFILING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_PROFILING:-false}"
export PLANSCAPE_FRONTEND_SENTRY_TRACES_SAMPLE_RATE="${PLANSCAPE_FRONTEND_SENTRY_TRACES_SAMPLE_RATE:-0.0}"
export PLANSCAPE_FRONTEND_SENTRY_PROFILING_SAMPLE_RATE="${PLANSCAPE_FRONTEND_SENTRY_PROFILING_SAMPLE_RATE:-0.0}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_CONTEXT_LINES="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_CONTEXT_LINES:-false}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_DEPRECATIONS_REPORTING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_DEPRECATIONS_REPORTING:-false}"
export PLANSCAPE_FRONTEND_GOOGLE_ANALYTICS_ID="${PLANSCAPE_FRONTEND_GOOGLE_ANALYTICS_ID:-}"
export PLANSCAPE_FRONTEND_MAPBOX_KEY="${PLANSCAPE_FRONTEND_MAPBOX_KEY:-}"
export PLANSCAPE_FRONTEND_OPEN_PANEL_KEY="${PLANSCAPE_FRONTEND_OPEN_PANEL_KEY:-}"
export PLANSCAPE_FRONTEND_MIXPANEL_TOKEN="${PLANSCAPE_FRONTEND_MIXPANEL_TOKEN:-}"
export PLANSCAPE_FRONTEND_SENTRY_DSN_URL="${PLANSCAPE_FRONTEND_SENTRY_DSN_URL:-}"

node <<'EOF'
const fs = require('fs');

function bool(name) {
  return String(process.env[name] ?? '').toLowerCase() === 'true';
}

function number(name) {
  const value = Number(process.env[name] ?? 0);
  return Number.isFinite(value) ? value : 0;
}

const environment = {
  environment: process.env.PLANSCAPE_FRONTEND_ENVIRONMENT,
  production: bool('PLANSCAPE_FRONTEND_PRODUCTION'),
  isCatalogEnvironment: bool('PLANSCAPE_FRONTEND_IS_CATALOG_ENVIRONMENT'),
  backend_endpoint: process.env.PLANSCAPE_FRONTEND_BACKEND_ENDPOINT,
  google_analytics_id: process.env.PLANSCAPE_FRONTEND_GOOGLE_ANALYTICS_ID,
  download_endpoint: process.env.PLANSCAPE_FRONTEND_DOWNLOAD_ENDPOINT,
  martin_server: process.env.PLANSCAPE_FRONTEND_MARTIN_SERVER,
  feature_flags: process.env.PLANSCAPE_FRONTEND_FEATURE_FLAGS,
  mapbox_key: process.env.PLANSCAPE_FRONTEND_MAPBOX_KEY,
  open_panel_key: process.env.PLANSCAPE_FRONTEND_OPEN_PANEL_KEY,
  open_panel_enabled: bool('PLANSCAPE_FRONTEND_OPEN_PANEL_ENABLED'),
  mixpanel_token: process.env.PLANSCAPE_FRONTEND_MIXPANEL_TOKEN,
  mixpanel_enabled: bool('PLANSCAPE_FRONTEND_MIXPANEL_ENABLED'),
  debug_layers: bool('PLANSCAPE_FRONTEND_DEBUG_LAYERS'),
  sentry: {
    dsn_url: process.env.PLANSCAPE_FRONTEND_SENTRY_DSN_URL,
    enable_extra_error_data: bool('PLANSCAPE_FRONTEND_SENTRY_ENABLE_EXTRA_ERROR_DATA'),
    enable_httpclient: bool('PLANSCAPE_FRONTEND_SENTRY_ENABLE_HTTPCLIENT'),
    enable_browser_reporting: bool('PLANSCAPE_FRONTEND_SENTRY_ENABLE_BROWSER_REPORTING'),
    enable_interventions_reporting: bool('PLANSCAPE_FRONTEND_SENTRY_ENABLE_INTERVENTIONS_REPORTING'),
    enable_crash_reporting: bool('PLANSCAPE_FRONTEND_SENTRY_ENABLE_CRASH_REPORTING'),
    enable_profiling: bool('PLANSCAPE_FRONTEND_SENTRY_ENABLE_PROFILING'),
    traces_sample_rate: number('PLANSCAPE_FRONTEND_SENTRY_TRACES_SAMPLE_RATE'),
    profiling_sample_rate: number('PLANSCAPE_FRONTEND_SENTRY_PROFILING_SAMPLE_RATE'),
    enable_context_lines: bool('PLANSCAPE_FRONTEND_SENTRY_ENABLE_CONTEXT_LINES'),
    enable_deprecations_reporting: bool('PLANSCAPE_FRONTEND_SENTRY_ENABLE_DEPRECATIONS_REPORTING'),
  },
};

fs.writeFileSync(
  'src/environments/environment.prod.ts',
  `export const environment = ${JSON.stringify(environment, null, 2)};\n`
);
EOF

npm run build -- --configuration production --output-path=dist/out

if [ "${PLANSCAPE_FRONTEND_UPLOAD_SOURCEMAPS:-false}" != "true" ]; then
  find dist/out -name '*.map' -delete
fi

destination="gs://${PLANSCAPE_FRONTEND_BUCKET}"
if [ -n "$PLANSCAPE_FRONTEND_BUCKET_PREFIX" ]; then
  destination="${destination}/${PLANSCAPE_FRONTEND_BUCKET_PREFIX#/}"
fi
destination="${destination%/}"

gsutil -m rsync -r -d dist/out "$destination"
gsutil -m setmeta -h "Cache-Control:public, max-age=31536000, immutable" "${destination}/**"
gsutil setmeta -h "Cache-Control:no-store, must-revalidate" "${destination}/index.html"
