# Generated by Django 4.2.21 on 2025-08-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("stands", "0002_auto_20250725_1720")]
    operations = [
        migrations.AddField(
            model_name="stand",
            name="grid_key",
            field=models.CharField(max_length=64, null=True, blank=True),
        ),
    ]
