# Generated by Django 4.1.10 on 2023-08-21 13:42

from django.db import migrations

from utils.file_utils import read_file


UP_MIGRATION = read_file("stands/sql/create_compute_stand_stats.sql")
DOWN_MIGRATION = "DROP FUNCTION compute_stand_stats;"


class Migration(migrations.Migration):
    dependencies = [
        ("stands", "0003_create_200ha_stands"),
    ]

    operations = [migrations.RunSQL(UP_MIGRATION, DOWN_MIGRATION)]
