# Generated by Django 4.1.10 on 2023-12-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stands", "0005_auto_20230823_1535"),
    ]

    operations = [
        migrations.AddField(
            model_name="standmetric",
            name="majority",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="standmetric",
            name="minority",
            field=models.FloatField(null=True),
        ),
    ]
