# Generated by Django 4.2.21 on 2025-08-22 11:18

from django.db import migrations
from pathlib import Path


def load_sql(apps, schema_editor):
    sql_path = (
        Path(__file__).resolve().parent.parent
        / "sql"
        / "create_dynamic_stands_for_planning_area.sql"
    )
    schema_editor.execute(sql_path.read_text(encoding="utf-8"))


def drop_sql(apps, schema_editor):
    schema_editor.execute(
        """
        DROP FUNCTION IF EXISTS public.generate_stands_for_planning_area(
            geometry, text, double precision, double precision
        );
    """
    )


class Migration(migrations.Migration):
    dependencies = [("stands", "0004_grid_key_unique_index")]
    operations = [
        migrations.RunPython(load_sql, reverse_code=drop_sql),
    ]
