# Generated by Django 4.2.21 on 2025-08-22 12:26

from django.db import migrations

SQL = """
DROP FUNCTION IF EXISTS public.create_stands(geometry, double precision, character varying, boolean);
DROP FUNCTION IF EXISTS public.generate_stand_metrics(integer, boolean);
DROP FUNCTION IF EXISTS public.compute_stand_stats(bigint, integer);
DROP TYPE IF EXISTS public.stand_stats;
"""

class Migration(migrations.Migration):
    atomic = False
    dependencies = [("stands", "0006_dynamic_stands_for_planning_area")]
    operations = [migrations.RunSQL(SQL, reverse_sql=migrations.RunSQL.noop)]