# Generated by Django 4.1.10 on 2023-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stands", "0006_standmetric_majority_standmetric_minority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stand",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="standmetric",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
