# Generated by Django 4.1.10 on 2024-02-21 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Owner", "Owner"),
                            ("Collaborator", "Collaborator"),
                            ("Viewer", "Viewer"),
                        ],
                        default="Viewer",
                        max_length=16,
                    ),
                ),
                ("permission", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="UserObjectRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Owner", "Owner"),
                            ("Collaborator", "Collaborator"),
                            ("Viewer", "Viewer"),
                        ],
                        default="Viewer",
                        max_length=16,
                    ),
                ),
                ("object_pk", models.PositiveIntegerField()),
                (
                    "collaborator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inviter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="permissions",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="unique_permission"
            ),
        ),
        migrations.AddConstraint(
            model_name="userobjectrole",
            constraint=models.UniqueConstraint(
                fields=("email", "content_type", "object_pk"),
                name="unique_collaborator",
            ),
        ),
    ]
