# Generated by Django 4.1.10 on 2024-01-25 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collaborator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("email", models.CharField(max_length=120)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Creator", "Creator"),
                            ("Owner", "Owner"),
                            ("Collaborator", "Collaborator"),
                            ("Viewer", "Viewer"),
                        ],
                        default="Viewer",
                        max_length=16,
                    ),
                ),
                (
                    "object_pk",
                    models.CharField(max_length=255, verbose_name="object ID"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Creator", "Creator"),
                            ("Owner", "Owner"),
                            ("Collaborator", "Collaborator"),
                            ("Viewer", "Viewer"),
                        ],
                        default="Viewer",
                        max_length=16,
                    ),
                ),
                ("permission", models.CharField(max_length=60)),
            ],
        ),
        migrations.AddConstraint(
            model_name="permissions",
            constraint=models.UniqueConstraint(
                fields=("role", "permission"), name="unique_permission"
            ),
        ),
        migrations.AddField(
            model_name="collaborator",
            name="collaborator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collaborator",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="collaborator",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inviter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="collaborator",
            constraint=models.UniqueConstraint(
                fields=("email", "content_type", "object_pk"),
                name="unique_collaborator",
            ),
        ),
    ]
