version: "3.9"

services:
  _planscape:
    image: planscape
    command: ["echo", "build done"]
    user: "${UID}:${GID}"
    environment:
      - UID=${UID}
      - GID=${GID}
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
  web:
    image: planscape
    extends:
      service: _planscape
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PORT: "8000"
    depends_on:
      - db
      - redis
    working_dir: /app/src/planscape
    command: bin/run_gunicorn.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    init: true
    stop_signal: SIGINT
    stop_grace_period: 30s
    ports:
      - "4200:8080"
    env_file:
      - .env
    depends_on:
      - web
    working_dir: /app/src/interface
    volumes:
      - .:/app
      - frontend_node_modules:/app/src/interface/node_modules
      - frontend_angular_cache:/app/src/interface/.angular
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      PLANSCAPE_FRONTEND_URL: "http://frontend:8080"
      PLANSCAPE_BACKEND_URL: "http://web:8000"
      PLANSCAPE_MARTIN_URL: "https://dev.planscape.org/tiles/"
    depends_on:
      - frontend
      - web
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data/redis
  celery_worker:
    image: planscape
    extends:
      service: _planscape
    working_dir: /app/src/planscape
    command: uv run celery -A planscape worker -E --loglevel INFO --concurrency 3 -Q forsys,default,impacts,geopackage,planning-stand-creation,planning-stand-metrics,climate-foresight
    deploy:
      replicas: 1
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    volumes:
      - .:/app
  celery_beat:
    image: planscape
    extends:
      service: _planscape
    working_dir: /app/src/planscape
    command: uv run celery -A planscape beat --loglevel INFO
    deploy:
      replicas: 1
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
      - celery_worker
    volumes:
      - .:/app
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_EXTENSIONS: postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    restart: unless-stopped
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
volumes:
  postgres: null
  cache:
    driver: local
  frontend_node_modules:
    driver: local
  frontend_angular_cache:
    driver: local
