FROM node:22.15.0-bullseye-slim

WORKDIR /app/src/interface

COPY src/interface/package.json src/interface/package-lock.json ./

RUN npm ci

COPY src/interface/ ./

CMD ["./node_modules/.bin/ng", "serve", "--host", "0.0.0.0", "--configuration", "docker"]
