FROM node:18.20-bullseye-slim

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN npm install -g @angular/cli

COPY src/interface/package.json src/interface/package-lock.json /usr/src/app/

RUN npm install

COPY .env Makefile /usr/src/app/
COPY src/interface/* /usr/src/app

CMD ["ng", "serve", "--host", "0.0.0.0"]