version: "3.9"

services:
  _planscape:
    image: planscape
    command: ["echo", "build done"]
    build:
      context: .
      dockerfile: docker/Dockerfile.arm64

  web:
    image: planscape
    extends:
      service: _planscape
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    working_dir: /usr/src/app/src/planscape
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/usr/src/app

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "4200:4200"
    env_file:
      - .env
    depends_on:
      - web
    working_dir: /usr/src/app/src/interface
    volumes:
      - .:/usr/src/app

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data/redis

  celery_worker:
    image: planscape
    extends:
      service: _planscape
    working_dir: /usr/src/app/src/planscape
    command: celery -A planscape worker -E --loglevel INFO --concurrency 3
    deploy:
      replicas: 2
    env_file:
      - .env
    depends_on:
      - web
      - db
      - redis
    volumes:
      - .:/usr/src/app

  db:
    # image: postgis/postgis:16-3.4
    image: kartoza/postgis:16-3.4--v2023.11.04
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./postgres-resources:/docker-entrypoint-initdb.d
      - ./data/pgopt:/opt/planscape/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      - "5433:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=planscapepw pg_isready -h 127.0.0.1 -U planscaper -d planscape"


volumes:
  postgres: null
  cache:
    driver: local
