#!/bin/sh
set -eu

export PORT="${PORT:-8080}"
export PLANSCAPE_FRONTEND_ENVIRONMENT="${PLANSCAPE_FRONTEND_ENVIRONMENT:-dev}"
export PLANSCAPE_FRONTEND_PRODUCTION="${PLANSCAPE_FRONTEND_PRODUCTION:-false}"
export PLANSCAPE_FRONTEND_IS_CATALOG_ENVIRONMENT="${PLANSCAPE_FRONTEND_IS_CATALOG_ENVIRONMENT:-false}"
export PLANSCAPE_FRONTEND_BACKEND_ENDPOINT="${PLANSCAPE_FRONTEND_BACKEND_ENDPOINT:-/planscape-backend}"
export PLANSCAPE_FRONTEND_GOOGLE_ANALYTICS_ID="${PLANSCAPE_FRONTEND_GOOGLE_ANALYTICS_ID:-}"
export PLANSCAPE_FRONTEND_DOWNLOAD_ENDPOINT="${PLANSCAPE_FRONTEND_DOWNLOAD_ENDPOINT:-}"
export PLANSCAPE_FRONTEND_MARTIN_SERVER="${PLANSCAPE_FRONTEND_MARTIN_SERVER:-/tiles/}"
export PLANSCAPE_FRONTEND_MAPBOX_KEY="${PLANSCAPE_FRONTEND_MAPBOX_KEY:-}"
export PLANSCAPE_FRONTEND_OPEN_PANEL_KEY="${PLANSCAPE_FRONTEND_OPEN_PANEL_KEY:-}"
export PLANSCAPE_FRONTEND_OPEN_PANEL_ENABLED="${PLANSCAPE_FRONTEND_OPEN_PANEL_ENABLED:-false}"
export PLANSCAPE_FRONTEND_MIXPANEL_TOKEN="${PLANSCAPE_FRONTEND_MIXPANEL_TOKEN:-}"
export PLANSCAPE_FRONTEND_MIXPANEL_ENABLED="${PLANSCAPE_FRONTEND_MIXPANEL_ENABLED:-false}"
export PLANSCAPE_FRONTEND_DEBUG_LAYERS="${PLANSCAPE_FRONTEND_DEBUG_LAYERS:-false}"
export PLANSCAPE_FRONTEND_SENTRY_DSN_URL="${PLANSCAPE_FRONTEND_SENTRY_DSN_URL:-}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_EXTRA_ERROR_DATA="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_EXTRA_ERROR_DATA:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_HTTPCLIENT="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_HTTPCLIENT:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_BROWSER_REPORTING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_BROWSER_REPORTING:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_INTERVENTIONS_REPORTING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_INTERVENTIONS_REPORTING:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_CRASH_REPORTING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_CRASH_REPORTING:-true}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_PROFILING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_PROFILING:-false}"
export PLANSCAPE_FRONTEND_SENTRY_TRACES_SAMPLE_RATE="${PLANSCAPE_FRONTEND_SENTRY_TRACES_SAMPLE_RATE:-0.0}"
export PLANSCAPE_FRONTEND_SENTRY_PROFILING_SAMPLE_RATE="${PLANSCAPE_FRONTEND_SENTRY_PROFILING_SAMPLE_RATE:-0.0}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_CONTEXT_LINES="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_CONTEXT_LINES:-false}"
export PLANSCAPE_FRONTEND_SENTRY_ENABLE_DEPRECATIONS_REPORTING="${PLANSCAPE_FRONTEND_SENTRY_ENABLE_DEPRECATIONS_REPORTING:-false}"

envsubst < /usr/share/nginx/html/assets/config.template.js > /usr/share/nginx/html/assets/config.js
envsubst '${PORT}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf

exec nginx -g 'daemon off;'
