# Generated by Django 4.1.1 on 2022-11-27 19:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CreateExtension("postgis"),
        CreateExtension("postgis_raster"),
        migrations.CreateModel(
            name="BaseCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition_name", models.CharField(max_length=120)),
                ("condition_level", models.IntegerField()),
                ("display_name", models.CharField(max_length=120, null=True)),
                ("region_name", models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConditionRaster",
            fields=[
                ("rid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(null=True)),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        null=True, srid=9822
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raster_name", models.TextField(null=True)),
                ("condition_score_type", models.IntegerField(null=True)),
                ("is_raw", models.BooleanField(null=True)),
                (
                    "condition_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conditions.basecondition",
                    ),
                ),
            ],
        ),
    ]
