# Generated by Django 4.1.1 on 2022-11-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbstractCondition',
            new_name='ConditionDataset',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='condition',
            new_name='condition_dataset',
        ),
    ]
