# Generated by Django 4.1.3 on 2022-11-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0001_conditionraster_remove_condition_geometry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionraster',
            options={'managed': True},
        ),
    ]
