# Generated by Django 4.1.3 on 2022-11-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_alter_conditionraster_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conditionraster',
            old_name='raster_name',
            new_name='name',
        ),
    ]
