# Generated by Django 4.1.1 on 2022-11-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0002_rename_abstractcondition_conditiondataset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConditionDataset',
            new_name='BaseCondition',
        ),
    ]
