# Generated by Django 4.1.3 on 2022-11-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0003_rename_raster_name_conditionraster_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionraster',
            options={'managed': False},
        ),
    ]
