# Generated by Django 4.1.10 on 2023-08-16 19:58

from django.db import migrations

UP_MIGRATION = """
ALTER SYSTEM SET postgis.enable_outdb_rasters TO TRUE;
ALTER SYSTEM SET postgis.gdal_enabled_drivers TO 'ENABLE_ALL';
"""


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0004_get_condition_pixels'),
    ]

    operations = [
        migrations.RunSQL(UP_MIGRATION)
    ]
