# Generated by Django 4.1.10 on 2023-08-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0005_alter_conditionraster_raster"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditionraster",
            name="condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raster_tiles",
                to="conditions.condition",
            ),
        ),
    ]
