# Generated by Django 4.1.10 on 2023-08-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0005_alter_conditionraster_raster'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='table_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
