# Generated by Django 4.1.10 on 2023-08-18 16:16

from django.db import migrations


UP_MIGRATION = """
CREATE INDEX conditions_conditionraster_raster_convexhull_idx ON conditions_conditionraster USING gist(ST_ConvexHull(raster));
"""

DOWN_MIGRATION = """
DROP INDEX IF EXISTS conditions_conditionraster_raster_convexhull_idx;
"""


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0006_conditionraster_condition"),
    ]

    operations = [
        migrations.RunSQL(UP_MIGRATION, DOWN_MIGRATION),
    ]
