# Generated by Django 4.1.10 on 2023-11-28 13:46

from django.db import migrations


def handle(apps, schema_editor):
    BaseCondition = apps.get_model("conditions", "BaseCondition")
    spotted_owl = BaseCondition.objects.filter(
        region_name="southern-california",
        display_name="California Spotted Owl",
        condition_name="wildlife_species_richness",
    )

    if spotted_owl.count() > 1:
        print("This migration is BAD! Check manually")
        return

    instance = spotted_owl.first()
    if instance:
        instance.condition_name = "california_spotted_owl"
        instance.save()


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0007_auto_20230818_1616"),
    ]

    operations = [migrations.RunPython(handle)]
