# Generated by Django 4.2.21 on 2025-09-10 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("planning", "0054_alter_treatmentgoalusesdatalayer_usage_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateForesight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the climate foresight analysis",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("running", "Running"),
                            ("done", "Done"),
                        ],
                        default="draft",
                        help_text="Current status of the analysis",
                        max_length=20,
                    ),
                ),
                (
                    "planning_area",
                    models.ForeignKey(
                        help_text="Planning area this analysis belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climate_foresight_analyses",
                        to="planning.planningarea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this analysis",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climate_foresight_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Climate Foresight Analysis",
                "verbose_name_plural": "Climate Foresight Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
