# Generated by Django 4.2.21 on 2025-10-08 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0020_auto_20250829_1648"),
        ("climate_foresight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateForesightRunInputDataLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "favor_high",
                    models.BooleanField(
                        help_text="True if high values are favorable, False if low values are favorable"
                    ),
                ),
                (
                    "pillar",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The pillar/category assignment for this layer",
                        max_length=255,
                    ),
                ),
                (
                    "datalayer",
                    models.ForeignKey(
                        help_text="Data layer being used as input",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="climate_foresight_inputs",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="Climate foresight run this input belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_datalayers",
                        to="climate_foresight.climateforesightrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Climate Foresight Run Input Data Layer",
                "verbose_name_plural": "Climate Foresight Run Input Data Layers",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="climateforesightruninputdatalayer",
            constraint=models.UniqueConstraint(
                fields=("run", "datalayer"),
                name="climateforesightruninputdatalayer_unique_constraint",
            ),
        ),
    ]
