# Generated by Django 4.2.21 on 2025-10-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climate_foresight", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="climateforesightrun",
            name="selected_data_layers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of selected data layer configurations. Each item contains: data_layer_id (int), favor_high (bool), pillar (str)",
                null=True,
            ),
        ),
    ]
