# Generated by Django 4.2.21 on 2025-10-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0020_auto_20250829_1648"),
        (
            "climate_foresight",
            "0003_alter_climateforesightruninputdatalayer_favor_high",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="climateforesightruninputdatalayer",
            name="normalized_datalayer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="climate_foresight_normalized_for",
                to="datasets.datalayer",
                help_text="The normalized version of this input data layer (for Climate Foresight analysis only)",
            ),
        ),
    ]
