# Generated by Django 5.2.7 on 2025-10-30 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climate_foresight", "0005_add_step_tracking_and_statistics"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateForesightPillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "name",
                    models.CharField(help_text="Name of the pillar", max_length=255),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order for the pillar"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this pillar",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_climate_foresight_pillars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="run_id",
                        help_text="If null, this is a global/shared pillar. If set, it's specific to that run.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_pillars",
                        to="climate_foresight.climateforesightrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Climate Foresight Pillar",
                "verbose_name_plural": "Climate Foresight Pillars",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="climateforesightpillar",
            constraint=models.UniqueConstraint(
                condition=models.Q(("run_id__isnull", True)),
                fields=("name",),
                name="unique_global_climate_foresight_pillar_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="climateforesightpillar",
            constraint=models.UniqueConstraint(
                condition=models.Q(("run_id__isnull", False)),
                fields=("run_id", "name"),
                name="unique_run_climate_foresight_pillar_name",
            ),
        ),
        migrations.RemoveField(
            model_name="climateforesightruninputdatalayer",
            name="pillar",
        ),
        migrations.AddField(
            model_name="climateforesightruninputdatalayer",
            name="pillar",
            field=models.ForeignKey(
                help_text="Optional pillar assignment for this data layer",
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datalayer_assignments",
                to="climate_foresight.climateforesightpillar",
            ),
        ),
    ]
