# Generated by Django 5.2.7 on 2025-11-06
from django.db import migrations
from django.utils import timezone
from django.conf import settings


def load_standard_pillars(apps, schema_editor):
    """
    Load the 10 standard fire resilience pillars.

    These are global pillars (run=None) that represent the standard
    framework for climate foresight analysis.
    """
    ClimateForesightPillar = apps.get_model(
        "climate_foresight", "ClimateForesightPillar"
    )
    User = apps.get_model("auth", "User")
    user = User.objects.get(email=settings.DEFAULT_ADMIN_EMAIL)

    pillars = [
        {"name": "Air Quality", "order": 1},
        {"name": "Carbon Sequestration", "order": 2},
        {"name": "Fire-Adapted Communities", "order": 3},
        {"name": "Forest and Shrubland Resilience", "order": 4},
        {"name": "Water Security", "order": 5},
        {"name": "Biodiversity Conservation", "order": 6},
        {"name": "Economic Diversity", "order": 7},
        {"name": "Fire Dynamics", "order": 8},
        {"name": "Social and Cultural Well-Being", "order": 9},
        {"name": "Wetland Integrity", "order": 10},
    ]

    for pillar_data in pillars:
        ClimateForesightPillar.objects.get_or_create(
            name=pillar_data["name"],
            run=None,  # Global pillars have no run
            defaults={
                "order": pillar_data["order"],
                "created_by": user,
                "created_at": timezone.now(),
            },
        )


def remove_standard_pillars(apps, schema_editor):
    """
    Reverse migration: remove the standard pillars.
    """
    ClimateForesightPillar = apps.get_model(
        "climate_foresight", "ClimateForesightPillar"
    )

    pillar_names = [
        "Air Quality",
        "Biodiversity Conservation",
        "Carbon Sequestration",
        "Economic Diversity",
        "Fire-Adapted Communities",
        "Fire Dynamics",
        "Forest and Shrubland Resilience",
        "Wetland Integrity",
        "Social and Cultural Well-Being",
        "Water Security",
    ]

    ClimateForesightPillar.objects.filter(
        name__in=pillar_names,
        run__isnull=True,  # only delete global pillars
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("climate_foresight", "0006_add_pillar_model"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(load_standard_pillars, remove_standard_pillars),
    ]
