# Generated by Django 5.2.7 on 2025-11-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climate_foresight", "0007_load_standard_pillars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climateforesightruninputdatalayer",
            name="favor_high",
            field=models.BooleanField(
                blank=True,
                help_text="True if high values are favorable, False if low values are favorable",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="climateforesightruninputdatalayer",
            name="normalized_datalayer",
            field=models.ForeignKey(
                help_text="The normalized version of this input data layer (for Climate Foresight analysis only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="climate_foresight_normalized_for",
                to="datasets.datalayer",
            ),
        ),
        migrations.AlterField(
            model_name="climateforesightruninputdatalayer",
            name="pillar",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional pillar assignment for this data layer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datalayer_assignments",
                to="climate_foresight.climateforesightpillar",
            ),
        ),
        migrations.AlterField(
            model_name="climateforesightruninputdatalayer",
            name="statistics",
            field=models.JSONField(
                blank=True,
                help_text="Statistics and normalization metadata. Structure: {  'original': {min, max, mean, std, count, percentiles: {p5, p10, p90, p95}},   'normalization': {transformation, original_skew, transformed_skew, outlier_min_p10, outlier_max_p90, favor_high}}",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClimateForesightPillarRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the rollup",
                        max_length=20,
                    ),
                ),
                (
                    "weights",
                    models.JSONField(
                        blank=True,
                        help_text="Weights used for rollup. Structure: {  'layer_id': weight_value,   'correlation_scores': {layer_id: correlation},   'method': 'optimized' or 'equal'}",
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("optimized", "Optimized"), ("equal", "Equal")],
                        default="optimized",
                        help_text="Weight calculation method used for rollup",
                        max_length=20,
                    ),
                ),
                (
                    "pillar",
                    models.ForeignKey(
                        help_text="Pillar that was rolled up",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rollups",
                        to="climate_foresight.climateforesightpillar",
                    ),
                ),
                (
                    "rollup_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="The rolled-up raster for this pillar (weighted average of normalized metrics)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_pillar_rollup",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        help_text="Climate foresight run this rollup belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillar_rollups",
                        to="climate_foresight.climateforesightrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Climate Foresight Pillar Rollup",
                "verbose_name_plural": "Climate Foresight Pillar Rollups",
                "ordering": ["pillar__order", "pillar__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "pillar"), name="unique_run_pillar_rollup"
                    )
                ],
            },
        ),
    ]
