# Generated by Django 5.2.7 on 2025-11-22 02:36

from django.db import migrations, models


def set_initial_status(apps, schema_editor):
    """
    Set initial status for existing input data layers.
    """
    ClimateForesightRunInputDataLayer = apps.get_model(
        "climate_foresight", "ClimateForesightRunInputDataLayer"
    )

    ClimateForesightRunInputDataLayer.objects.filter(
        normalized_datalayer__isnull=False
    ).update(status="completed")


class Migration(migrations.Migration):
    dependencies = [
        ("climate_foresight", "0008_add_pillar_rollup_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="climateforesightruninputdatalayer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Current processing status of this input data layer",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_initial_status, migrations.RunPython.noop),
    ]
