# Generated by Django 5.2.7 on 2025-11-05 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("climate_foresight", "0009_add_input_datalayer_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climateforesightruninputdatalayer",
            name="pillar",
            field=models.ForeignKey(
                help_text="Optional pillar assignment for this data layer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datalayer_assignments",
                to="climate_foresight.climateforesightpillar",
            ),
        ),
        migrations.CreateModel(
            name="ClimateForesightLandscapeRollup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the landscape rollup",
                        max_length=20,
                    ),
                ),
                (
                    "future_mapping",
                    models.JSONField(
                        blank=True,
                        help_text="Maps pillar_id to future climate layer_id used. Structure: {pillar_id: {layer_id: X, matched: true/false, default: true/false}}",
                        null=True,
                    ),
                ),
                (
                    "current_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aggregated current conditions landscape raster (0-100)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_current_landscape",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "future_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Aggregated future conditions landscape raster (0-100)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_future_landscape",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        help_text="Climate foresight run this landscape rollup belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landscape_rollup",
                        to="climate_foresight.climateforesightrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Climate Foresight Landscape Rollup",
                "verbose_name_plural": "Climate Foresight Landscape Rollups",
            },
        ),
        migrations.CreateModel(
            name="ClimateForesightPromote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the PROMOTe analysis",
                        max_length=20,
                    ),
                ),
                (
                    "adapt_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Adapt strategy score (0-100)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_adapt",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "adapt_protect_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Adapt-Protect score (0-100, rescaled)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_adapt_protect",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "integrated_condition_score_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Integrated Condition Score (0-100)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_ics",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "monitor_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Monitor strategy score (0-100)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_monitor",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "mpat_matrix_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="MPAT Matrix - categorical (1=Monitor, 2=Protect, 3=Adapt, 4=Transform)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_mpat_matrix",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "mpat_strength_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="MPAT with strength classification (weak/strong)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_mpat_strength",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "protect_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Protect strategy score (0-100)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_protect",
                        to="datasets.datalayer",
                    ),
                ),
                (
                    "run",
                    models.OneToOneField(
                        help_text="Climate foresight run this PROMOTe analysis belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promote_analysis",
                        to="climate_foresight.climateforesightrun",
                    ),
                ),
                (
                    "transform_datalayer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transform strategy score (0-100)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="climate_foresight_transform",
                        to="datasets.datalayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Climate Foresight PROMOTe Analysis",
                "verbose_name_plural": "Climate Foresight PROMOTe Analyses",
            },
        ),
    ]
