# Generated by Django 5.2.7 on 2025-12-09 01:59

from django.db import migrations, models


def initialize_geopackage_status(apps, schema_editor):
    """Initialize geopackage_status to PENDING for all completed PROMOTe analyses."""
    ClimateForesightPromote = apps.get_model("climate_foresight", "ClimateForesightPromote")

    ClimateForesightPromote.objects.filter(
        status="completed"
    ).update(geopackage_status="PENDING")


class Migration(migrations.Migration):
    dependencies = [
        ("climate_foresight", "0011_create_internal_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="climateforesightpromote",
            name="geopackage_status",
            field=models.CharField(
                choices=[
                    ("SUCCEEDED", "Succeeded"),
                    ("PROCESSING", "Processing"),
                    ("PENDING", "Pending"),
                    ("FAILED", "Failed"),
                ],
                help_text="Status of the geopackage generation.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="climateforesightpromote",
            name="geopackage_url",
            field=models.URLField(
                help_text="Cloud storage URL of the generated geopackage ZIP file.",
                null=True,
            ),
        ),
        migrations.RunPython(initialize_geopackage_status),
    ]
