# Generated by Django 5.2.7 on 2025-12-10
from django.db import migrations


def update_pillar_names(apps, schema_editor):
    """
    Update global pillar names to remove hyphens
    """
    ClimateForesightPillar = apps.get_model(
        "climate_foresight", "ClimateForesightPillar"
    )

    ClimateForesightPillar.objects.filter(
        name="Fire-Adapted Communities",
        run__isnull=True,
    ).update(name="Fire Adapted Communities")

    ClimateForesightPillar.objects.filter(
        name="Social and Cultural Well-Being",
        run__isnull=True,
    ).update(name="Social and Cultural Wellbeing")


def revert_pillar_names(apps, schema_editor):
    """
    Revert global pillar names to original hyphenated versions.
    """
    ClimateForesightPillar = apps.get_model(
        "climate_foresight", "ClimateForesightPillar"
    )

    ClimateForesightPillar.objects.filter(
        name="Fire Adapted Communities",
        run__isnull=True,
    ).update(name="Fire-Adapted Communities")

    ClimateForesightPillar.objects.filter(
        name="Social and Cultural Wellbeing",
        run__isnull=True,
    ).update(name="Social and Cultural Well-Being")


class Migration(migrations.Migration):
    dependencies = [
        (
            "climate_foresight",
            "0012_climateforesightpromote_geopackage_status_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(update_pillar_names, revert_pillar_names),
    ]
