---
title: "Path to Target Conditions"
author: "Laurens Geffert"
date: "2022-11-14"
output: rmarkdown::github_document
---

First I load the TCSI data at pillar level:

```{r loading}

library(sf)
library(raster)
library(tidyverse)
library(magrittr)
library(purrr)

# Select HUC12 planning area
HUC12 = 3436
run_label = 'TCSI_downsample'

current_forres <- raster('../data/TCSI/forestResilience/tif/current.tif')
current_firdyn <- max(
  raster('../data/TCSI/fireDynamics/tif/current.tif'),
  raster('../data/TCSI/fireAdaptedComm/tif/current.tif'), na.rm = TRUE)
current_carbon <- raster('../data/TCSI/carbon/tif/current.tif')
current_biodiv <- raster('../data/TCSI/biodiversity/tif/current.tif')

future_forres <- raster('../data/TCSI/forestResilience/tif/future.tif')
future_firdyn <- max(
  raster('../data/TCSI/fireDynamics/tif/future.tif'),
  raster('../data/TCSI/fireAdaptedComm/tif/future.tif'), na.rm = TRUE)
future_carbon <- raster('../data/TCSI/carbon/tif/future.tif')
future_biodiv <- raster('../data/TCSI/biodiversity/tif/future.tif')
```

I am re-sampling the rasters to a coarser resolution to make the overall analysis run faster. This can be removed at a later stage once the analysis flow is finalized.

```{r resampling}
inputs <- c(
  'current_forres',
  'current_firdyn',
  'current_carbon',
  'current_biodiv',
  'future_forres',
  'future_firdyn',
  'future_carbon',
  'future_biodiv')

for(input in inputs) {
  assign(input, aggregate(get(input), 4))
}

rast <- stack(
  current_forres,
  current_firdyn,
  current_carbon,
  current_biodiv,
  future_forres,
  future_firdyn,
  future_carbon,
  future_biodiv)

names(rast) <- inputs

write_rds(rast, '../output/pillar_data_resampled_stacked.rds')
```

```{r stacking}
df <- rast %>%
  values() %>%
  as_tibble() %>%
  # drop all rows that only contain NA
  filter(if_any(everything(), ~ !is.na(.))) %>%
  # introducing sampling to generate plots faster
  sample_n(100000)
```

```{r plot_histograms}
df %>%
  pivot_longer(cols = everything()) %>%
  mutate(
    context = case_when(
      str_detect(name, 'current') ~ 'current',
      str_detect(name, 'future') ~ 'future',
      TRUE ~ as.character(NA)),
    name = name %>%
      str_remove('current_') %>%
      str_remove('future_')) %>%
  filter(complete.cases(.)) %>%
  ggplot(aes(x = value)) +
  geom_histogram() +
  facet_grid(context ~ name)
```

```{r plot_scatter_1}
df %>%
  filter(complete.cases(.)) %>%
  ggplot(aes(x = current_forres, y = current_carbon)) +
  geom_point(alpha = .01)
```

Some trade-off between forest resilience and biomass.


```{r plot_scatter_2}
df %>%
  filter(complete.cases(.)) %>%
  ggplot(aes(x = current_forres, y = current_biodiv)) +
  geom_point(alpha = .01)
```



```{r plot_scatter_3}
df %>%
  filter(complete.cases(.)) %>%
  ggplot(aes(x = current_carbon, y = current_biodiv)) +
  geom_point(alpha = .01)
```


```{r plot_scatter_4}
df %>%
  filter(complete.cases(.)) %>%
  sample_n(1000) %>%
  select(current_forres, future_forres, current_biodiv, future_biodiv) %>%
  mutate(grouping = row_number()) %>%
  pivot_longer(-grouping) %>%
  mutate(
    context = case_when(
      str_detect(name, 'current') ~ 'current',
      str_detect(name, 'future') ~ 'future',
      TRUE ~ as.character(NA)),
    name = name %>%
      str_remove('current_') %>%
      str_remove('future_')) %>%
  pivot_wider(names_from = name, values_from = value) %>%
  ggplot(aes(x = forres, y = biodiv)) +
  geom_point(aes(color = context), alpha = 0.5) +
  geom_line(aes(group = grouping), alpha = 0.1)

```

```{r plot_scatter_5}
df %>%
  filter(complete.cases(.)) %>%
  ggplot(aes(x = current_forres, y = future_forres)) +
  geom_point(alpha = .01)
```

Let's try to look within climate class so that we compare apples with apples.

```{r}
climate_class <- st_read('../data/TCSI/ClimClass_TCSI/ClimateClasses_15m_TCSI_wClasses_LL.shp')

plot(climate_class[,c(1,8)])
plot(rast$current_forres, add = TRUE)



r <- raster(x = extent(current_forres), ncol=ncol(current_forres), nrow=nrow(current_forres), crs=crs(current_forres))
climate_class_raster <- climate_class %>%
  raster::rasterize(y = r, field = climate_class$Id, fun = last, na.rm = TRUE)#, filename = '../output/climate_class_raster.tif')


climate_class_raster <- climate_class %>%
  transmute(value = Id, geometry = geometry) %>%
  raster::rasterize(rast, field = climate_class$Id)

r <- dim(rast)[1:2]




rast2 <- stack(rast, climate_class)
names(rast2)[length(names(rast2))] <- 'climate_class'

r_new <- rasterize(x = data.df[,1:2], y = r, data.df[,3], fun = mean)

```



```{r}
df %>%
  select(current_forres, current_firdyn, current_carbon) %>%
  mutate(context = 'current') %>%
  bind_rows(
    df %>% select()
  ) %>%
```

```{r}

df %>%
  filter(complete.cases(.))

```





```{r}
x <- df %>%
  mutate(id = row_number()) %>%
  pivot_longer(cols = -id, names_to = 'var')

x2 <- inner_join(x, x, by = 'id') %>%
  filter(complete.cases(.)) %>%
  filter(
    var.x %in% c('current_forres', 'current_biodiv') &
    var.y %in% c('current_forres', 'current_biodiv'))

x2 %>%
  ggplot(aes(x = value.x, y = value.y)) +
  facet_grid(var.x ~ var.y, scales = 'free') +
  stat_density_2d(
    geom = 'raster',
    aes(fill = after_stat(density)),
    contour = FALSE) +
  scale_fill_viridis_c()
```


