# Generated by Django 4.1.1 on 2022-09-25 12:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCSI_HUC12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('tnmid', models.CharField(max_length=40)),
                ('metasource', models.CharField(max_length=40)),
                ('sourcedata', models.CharField(max_length=100)),
                ('sourceorig', models.CharField(max_length=130)),
                ('sourcefeat', models.CharField(max_length=40)),
                ('loaddate', models.DateField()),
                ('noncontrib', models.FloatField()),
                ('noncontr_1', models.FloatField()),
                ('areasqkm', models.FloatField()),
                ('areaacres', models.FloatField()),
                ('gnis_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('states', models.CharField(max_length=50)),
                ('huc12', models.CharField(max_length=12)),
                ('hutype', models.CharField(max_length=254)),
                ('humod', models.CharField(max_length=30)),
                ('tohuc', models.CharField(max_length=16)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('hectares', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269)),
            ],
        ),
    ]
