# Generated by Django 4.1.1 on 2022-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_tcsi_huc12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcsi_huc12',
            name='metasource',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
