# Generated by Django 4.1.1 on 2022-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_alter_tcsi_huc12_metasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcsi_huc12',
            name='sourcedata',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tcsi_huc12',
            name='sourcefeat',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tcsi_huc12',
            name='sourceorig',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
