# Generated by Django 4.1.1 on 2022-10-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_alter_tcsi_huc12_sourcedata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
