FROM arm64v8/node:current-bullseye-slim

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY src/interface/package.json src/interface/package-lock.json /usr/src/app/

RUN npm install -g @angular/cli@17.3.8

RUN npm install @angular-devkit/build-angular@17.3.8 --save-dev --force

RUN npm install

COPY . /usr/src/app

CMD ["ng", "serve", "--host", "0.0.0.0"]
