# Generated by Django 5.2.7 on 2026-05-07 18:35
from datetime import datetime
from django.db import migrations


def create_initial_entry(apps, schema_editor):
    RestoreBackTrack = apps.get_model("core", "RestoreBackTrack")
    date_str = "2026-04-01 00:00:00"
    date_obj = datetime.strptime(date_str, "%Y-%m-%d %H:%M:%S")
    RestoreBackTrack.objects.create(
        file_name="initial",
        started_at=date_obj,
        finished_at=date_obj,
        status="SUCCESS"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
         migrations.RunPython(create_initial_entry, migrations.RunPython.noop),
    ]
