# Generated by Django 4.1.10 on 2023-08-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planningarea",
            name="notes",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
