# Generated by Django 4.1.10 on 2023-08-31 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0002_planningarea_notes_scenario_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenarioresult",
            name="scenario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="planning.scenario",
            ),
        ),
    ]
