# Generated by Django 4.1.10 on 2023-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0003_alter_scenarioresult_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenarioresult",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="scenarioresult",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
