# Generated by Django 4.1.11 on 2023-10-27 22:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0005_alter_scenarioresult_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
