# Generated by Django 4.1.10 on 2023-12-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0009_alter_scenarioresult_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planningarea",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="scenarioresult",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
