# Generated by Django 4.1.11 on 2024-01-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0010_alter_planningarea_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenarioresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("PANIC", "Panic"),
                    ("TIMED_OUT", "Timed Out"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
