# Generated by Django 4.1.11 on 2024-01-04 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import planning.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planning", "0010_alter_planningarea_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "link_code",
                    models.CharField(
                        default=planning.models.generate_short_uuid,
                        max_length=10,
                    ),
                ),
                ("view_state", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="shared_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "user"],
            },
        ),
    ]
