# Generated by Django 4.1.11 on 2024-01-04 17:54

from django.db import migrations, models
import planning.models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0011_sharedlink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedlink",
            name="clicked_count",
        ),
        migrations.AlterField(
            model_name="sharedlink",
            name="link_code",
            field=models.CharField(
                default=planning.models.SharedLink.generate_random_string,
                max_length=100,
            ),
        ),
    ]
