# Generated by Django 4.1.10 on 2024-01-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0012_sharedlink"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Creator", "Creator"),
                            ("Owner", "Owner"),
                            ("Collaborator", "Collaborator"),
                            ("Viewer", "Viewer"),
                        ],
                        default="Viewer",
                        max_length=16,
                    ),
                ),
                ("permission", models.CharField(max_length=60)),
            ],
        ),
    ]
