# Generated by Django 4.1.10 on 2024-02-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0013_scenario_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                default="ACTIVE",
                max_length=32,
            ),
        ),
    ]
