# Generated by Django 4.1.10 on 2024-02-15 19:36

import collaboration.permissions
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0002_add_permissions"),
        ("planning", "0013_scenario_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningAreaCollaborator",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=(
                "collaboration.collaborator",
                collaboration.permissions.CheckPermissionMixin,
            ),
        ),
    ]
