# Generated by Django 4.1.10 on 2024-02-15 17:42

import collaboration.permissions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collaboration", "0002_add_permissions"),
        ("planning", "0013_scenario_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningAreaCollaborator",
            fields=[
                (
                    "collaborator_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="collaboration.collaborator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                "collaboration.collaborator",
                collaboration.permissions.CheckPermissionMixin,
            ),
        ),
    ]
