# Generated by Django 4.1.10 on 2024-01-25 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0014_collaborator_permissions_unique_permission_and_more"),
    ]
    def insertData(apps, schema_editor):
        viewer = ['view_planning_area','view_scenario']
        collaborator = viewer + ['add_scenario']
        owner = collaborator + ['add_collaborator', 'delete_collaborator', 'change_collaborator']
        creator = collaborator + ['delete_planning_area']
        Permission = apps.get_model("planning", "Permissions")
        for x in viewer:
            entry = Permission(role = 'VIEWER', permission = x)
            entry.save()

        for x in collaborator:
            entry = Permission(role = 'COLLABORATOR', permission = x)
            entry.save()

        for x in owner:
            entry = Permission(role = 'OWNER', permission = x)
            entry.save()

        for x in creator:
            entry = Permission(role = 'CREATOR', permission = x)
            entry.save()
       
    operations = [
        migrations.RunPython(insertData),
    ]