# Generated by Django 4.1.10 on 2024-03-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0014_scenario_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planningarea",
            name="region_name",
            field=models.CharField(
                choices=[
                    ("sierra-nevada", "Sierra Nevada"),
                    ("southern-california", "Southern California"),
                    ("central-coast", "Central Coast"),
                    ("northern-california", "Northern California"),
                ],
                max_length=120,
            ),
        ),
    ]
