# Generated by Django 4.1.11 on 2024-03-14 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("planning", "0015_alter_planningarea_region_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningAreaNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(null=True)),
                (
                    "planning_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_area",
                        to="planning.planningarea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="planningareanote",
            index=models.Index(fields=["user"], name="planning_pl_user_id_957f36_idx"),
        ),
    ]
