# Generated by Django 4.2.14 on 2024-11-26 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("impacts", "0016_alter_treatmentplan_status"),
        ("planning", "0026_alter_planningareanote_planning_area_projectareanote"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectareanote",
            name="treatment_plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatment_plan",
                to="impacts.treatmentplan",
            ),
        ),
    ]
