# Generated by Django 4.2.19 on 2025-04-14 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0032_remove_treatmentgoalusesdatalayer_constraints_and_more"),
    ]

    operations = [
        migrations.RunSQL("SELECT setval('planning_treatmentgoal_id_seq', 100); ") 
    ]
