# Generated by Django 4.2.19 on 2025-05-20 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0035_auto_20250505_2006"),
    ]

    operations = []
