# Generated by Django 4.2.19 on 2025-05-20 15:35

from django.db import migrations


def backfill_scenario_configuration_keys(apps, schema_editor):
    Scenario = apps.get_model("planning", "Scenario")
    
    for scenario in Scenario.objects.iterator(chunk_size=100):
        configuration = scenario.configuration
        if "estimated_cost" not in configuration:
            estimated_cost = configuration.pop("est_cost", None)
            configuration["estimated_cost"] = estimated_cost
        if "max_area" not in configuration:
            max_area = configuration.pop("max_treatment_area_ratio", None)
            configuration["max_area"] = max_area
        scenario.configuration = configuration
        scenario.save(update_fields=["configuration"])


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0035_auto_20250505_2006"),
    ]

    operations = [
        migrations.RunPython(backfill_scenario_configuration_keys)
    ]
