# Generated by Django 4.2.21 on 2025-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0037_auto_20250520_2034"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planningarea",
            name="region_name",
            field=models.CharField(
                choices=[
                    ("sierra-nevada", "Sierra Nevada"),
                    ("southern-california", "Southern California"),
                    ("central-coast", "Central Coast"),
                    ("northern-california", "Northern California"),
                ],
                help_text="Region choice name of the Planning Area.",
                max_length=120,
                null=True,
            ),
        ),
    ]
