# Generated by Django 4.2.21 on 2025-07-31 17:24

from django.db import migrations


def backfill_treatment_goal_group(apps, schema_editor):
    TreatmentGoal = apps.get_model("planning", "TreatmentGoal")

    # Backfill the group field for existing TreatmentGoals
    for tx_goal in TreatmentGoal.objects.all():
        datalayers = tx_goal.datalayers.all()
        group = "WILDFIRE_RISK_TO_COMMUNITIES"
        if datalayers.filter(dataset__name="California Regional Resource Kit").exists():
            group = "CALIFORNIA_PLANNING_METRICS"
        tx_goal.group = group
        tx_goal.save(update_fields=["group"])


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0040_treatmentgoal_group"),
    ]

    operations = [
        migrations.RunPython(backfill_treatment_goal_group),
    ]
