# Generated by Django 4.2.21 on 2025-09-11 15:20

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0049_scenario_forsys_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="capabilities",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Computed feature flags/capabilities for this Scenario.",
                null=True,
            ),
        ),
    ]
