# Generated by Django 4.2.21 on 2025-09-16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0052_alter_planningarea_map_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenario",
            name="capabilities",
        ),
        migrations.AddField(
            model_name="scenario",
            name="capabilities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("FORSYS", "Forsys"),
                        ("IMPACTS", "Impacts"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
                help_text="List of enabled capabilities for this Scenario.",
                size=None,
            ),
        ),
    ]