# Generated by Django 4.2.21 on 2025-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0059_add_new_treatment_goals_timber_crown_mortality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentgoal",
            name="group",
            field=models.CharField(
                choices=[
                    ("WILDFIRE_RISK_TO_COMMUTIES", "Wildfire Risk to Communities"),
                    ("CALIFORNIA_PLANNING_METRICS", "California Planning Metrics"),
                    ("TREEMAP_FVS_2020", "TreeMap FVS 2020"),
                    ("PYROLOGIX", "Pyrologix"),
                ],
                help_text="Treatment Goal group.",
                max_length=64,
                null=True,
            ),
        ),
    ]
