# Generated by Django 5.2.7 on 2025-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0061_rebin_conus_goals_timber_crown_mortality"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planningarea",
            name="map_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("STANDS_DONE", "Stands Done"),
                    ("DONE", "Done"),
                    ("FAILED", "Failed"),
                    ("OVERSIZE", "Oversize (>3M Acres)"),
                ],
                help_text="Controls the status of all the processes needed to allow the dynamic map to work.",
                null=True,
            ),
        ),
    ]
