# Generated by Django 5.2.7 on 2025-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0066_update_enum_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="ready_email_sent_at",
            field=models.DateTimeField(
                help_text="When the ready email was sent.", null=True
            ),
        ),
    ]
