# Generated by Django 4.2.21 on 2025-10-18

from django.db import migrations

ROW_FETCH_CHUNK_SIZE = 1000


def recalculate_planning_area_capabilities(apps, schema_editor):
    from modules.base import compute_planning_area_capabilities
    from planning.models import PlanningArea

    for planning_area in PlanningArea.objects.all().iterator(
        chunk_size=ROW_FETCH_CHUNK_SIZE
    ):
        planning_area.capabilities = compute_planning_area_capabilities(planning_area)
        planning_area.save(update_fields=["capabilities"])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("planning", "0074_planningarea_capabilities_and_more"),
    ]

    operations = [
        migrations.RunPython(
            recalculate_planning_area_capabilities,
            migrations.RunPython.noop,
        ),
    ]
