# Generated by Django 5.2.7 on 2026-02-20 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0081_make_scenario_name_unique_only_for_alive_rows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treatmentgoalusesdatalayer",
            name="weight",
            field=models.PositiveIntegerField(
                help_text="Only applies when Usage Type = PRIORITY. Must be a positive integer (>= 1).",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
