# Generated by Django 5.2.7 on 2026-02-20 19:09

from django.db import migrations

BATCH_SIZE = 1000

def backfill_scenarios_planning_approach(apps, schema_editor):
    Scenario = apps.get_model("planning", "Scenario")

    scenarios_queryset = Scenario.objects.filter(planning_approach__isnull=True)
    
    while True:
        scenario_ids_batch = list(
            scenarios_queryset.values_list("id", flat=True)[:BATCH_SIZE]
        )
        if not scenario_ids_batch:
            break

        Scenario.objects.filter(id__in=scenario_ids_batch).update(planning_approach="OPTIMIZE_PROJECT_AREAS")


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0082_alter_treatmentgoalusesdatalayer_weight"),
    ]

    operations = [
        migrations.RunPython(backfill_scenarios_planning_approach, migrations.RunPython.noop),
    ]
