# Generated by Django 5.2.7 on 2026-04-24 19:34

from django.db import migrations
from planning.services import get_min_project_area


def backfill_scenarios_rx_leverage_and_pct_treatable_area(apps, schema_editor):
    Scenario = apps.get_model("planning", "Scenario")
    DataLayer = apps.get_model("dataset", "DataLayer")

    scenarios_queryset = Scenario.objects.filter(result_status="SUCCESS")
    
    for scenario in scenarios_queryset:
        results = scenario.results
        features = results.result.get("features")
        if scenario.type == "CUSTOM":
            cfg = scenario.configuration or {}
            priority_ids = cfg.get("priority_objectives")
            names = DataLayer.objects.filter(pk__in=priority_ids).values_list("name")
        else:
            names = scenario.treatment_goal.datalayer_usages.filter(
                usage_type="PRIORITY"
            ).values_list("datalayer__name")
        names = [name[0] for name in names]

        forsys_input = scenario.forsys_input or {}
        number_of_stands = len(forsys_input.get("stand_ids", []))
        stand_area = get_min_project_area(scenario=scenario)

        treatable_area = number_of_stands * stand_area

        for feature in features:
            # Rx Leverage Backfill
            attainment = feature.get("properties").get("attainment")
            att_values = [attainment.get(name) for name in names]
            area_acres = feature.get("properties").get("area_acres")
            rx_leverage = (sum(att_values) / area_acres) * 1000 if area_acres else None
            feature["properties"]["rx_leverage"] = rx_leverage

            # PCT Treatable Area Backfill
            proj_area_acres = feature.get("properties").get("area_acres")
            pct_treatable_area = proj_area_acres / treatable_area if treatable_area else None
            feature["properties"]["pct_treatable_area"] = pct_treatable_area

        results.result["features"] = features
        results.save(update_fields=["result"])


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0088_remove_planning_area_scenario_count"),
    ]

    operations = [migrations.RunPython(backfill_scenarios_rx_leverage_and_pct_treatable_area, migrations.RunPython.noop)]
