install.packages("dplyr")
install.packages("textshaping")
install.packages("stringi")
install.packages("ggnewscale")
install.packages("udunits2")
install.packages("sf")
install.packages("ragg")
install.packages("pkgdown")
install.packages("devtools")
install.packages("DBI")
install.packages("RPostgreSQL")
install.packages("optparse")
install.packages("rjson")
install.packages("glue")
install.packages("purrr")
install.packages("dplyr")
install.packages("logger")

library("devtools")

devtools::install_github("forsys-sp/forsysr")
devtools::install_github("forsys-sp/patchmax")
