server {
    listen ${PORT};
    server_name _;

    gzip on;
    gzip_types text/plain application/javascript application/json text/javascript text/xml text/css image/svg+xml;
    gzip_min_length 1000;

    client_max_body_size 50M;

    proxy_http_version 1.1;
    proxy_ssl_server_name on;
    proxy_redirect off;

    proxy_set_header Connection "";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;

    location /planscape-backend/ {
        expires off;
        proxy_pass ${PLANSCAPE_BACKEND_URL};
    }

    location /s3/ {
        expires off;
        proxy_pass ${PLANSCAPE_BACKEND_URL};
    }

    location ~ ^/tiles/(?<fwd_path>.*) {
        if ($request_method = 'OPTIONS') {
            add_header Cache-Control "public, max-age=1728000, no-transform" always;
            add_header Access-Control-Allow-Origin "$http_origin" always;
            add_header Access-Control-Allow-Methods 'GET, POST, OPTIONS' always;
            add_header Access-Control-Allow-Headers 'Authorization, Origin, X-Requested-With, Content-Type, Accept' always;
            add_header Access-Control-Allow-Credentials 'true' always;
            add_header Access-Control-Max-Age 1728000 always;
            add_header Content-Type 'text/plain; charset=utf-8' always;
            add_header Content-Length 0 always;
            return 204;
        }

        auth_request /auth-proxy;
        auth_request_set $auth_status $upstream_status;

        add_header Access-Control-Allow-Headers 'Authorization, Origin, X-Requested-With, Content-Type, Accept' always;
        proxy_pass ${PLANSCAPE_MARTIN_URL}/$fwd_path$is_args$args;
    }

    location = /auth-proxy {
        internal;

        proxy_pass ${PLANSCAPE_BACKEND_URL}/planscape-backend/users/validate_martin_request;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header Cookie $http_cookie;
        proxy_set_header Authorization $http_authorization;
    }

    location / {
        proxy_pass ${PLANSCAPE_FRONTEND_URL};
    }
}
