# Generated by Django 4.1.3 on 2023-03-17 22:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension('postgis'),
        CreateExtension('postgis_raster'),
        migrations.CreateModel(
            name="AttributeRaster",
            fields=[
                ("rid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(null=True)),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        null=True, srid=9822
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attribute_name", models.CharField(max_length=120)),
                ("display_name", models.CharField(max_length=120, null=True)),
                ("region_name", models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raster_name", models.TextField(null=True)),
                (
                    "attribute_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attributes.baseattribute",
                    ),
                ),
            ],
        ),
    ]
