# Generated by Django 4.1.10 on 2023-12-04 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, null=True)),
                ("type", models.CharField(max_length=128)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4269),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="restriction",
            index=models.Index(fields=["type"], name="restriction_type_index"),
        ),
    ]
