# Generated by Django 4.1.1 on 2022-11-08 14:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from typing import Tuple


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.RasterField(
                    null=True, srid=9822)),
                ('filename', models.TextField(null=True)),
            ],
            options={
                'db_table': 'wms_current',
                'managed': False,
            },
        ),
    ]
