# Generated by Django 4.1.3 on 2023-02-08 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conditions", "0003_get_condition_stats"),
        ("plan", "0008_projectarea_owner"),
    ]

    operations = []
