# Generated by Django 4.1.3 on 2023-01-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_conditionscores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='max_cost',
        ),
        migrations.AddField(
            model_name='project',
            name='max_budget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_road_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_slope',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='max_treatment_ratio',
            field=models.FloatField(null=True),
        ),
    ]
