# Generated by Django 4.1.1 on 2023-02-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0010_remove_project_max_cost_project_max_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="creation_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
