# Generated by Django 4.1.3 on 2023-01-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_remove_project_max_cost_project_max_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='max_treatment_ratio',
            new_name='max_treatment_area_ratio',
        ),
    ]
