# Generated by Django 4.1.3 on 2023-02-08 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conditions", "0003_get_mean_condition_score"),
        ("plan", "0011_rename_max_treatment_ratio_project_max_treatment_area_ratio"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightedPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField()),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conditions.condition",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.scenario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RankedProjectArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("total_weighted_priority_score", models.FloatField(null=True)),
                (
                    "project_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan.projectarea",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.scenario"
                    ),
                ),
            ],
        ),
    ]
