# Generated by Django 4.1.3 on 2023-02-15 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0012_scenario_creation_time_scenario_max_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenario",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan.project",
            ),
        ),
    ]
