# Generated by Django 4.1.3 on 2023-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0013_alter_scenario_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="notes",
            field=models.TextField(null=True),
        ),
    ]
