# Generated by Django 4.1.3 on 2023-03-01 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('plan', '0016_config_rankedprojectarea_configpriority_and_more'), ('plan', '0017_remove_projectarea_scenario_and_more'), ('plan', '0018_rename_score_rankedprojectarea_weighted_score')]

    dependencies = [
        ('conditions', '0004_get_condition_pixels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plan', '0015_remove_scenario_max_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedProjectArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('weighted_score', models.FloatField()),
                ('project_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.projectarea')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditions.condition')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectarea',
            name='scenario',
        ),
        migrations.AddField(
            model_name='scenario',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Processed'), (3, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='priorities',
            field=models.ManyToManyField(through='plan.ConfigPriority', to='conditions.condition'),
        ),
        migrations.AlterField(
            model_name='scenarioweightedpriority',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.configpriority'),
        ),
    ]
