# Generated by Django 4.1.3 on 2023-02-27 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("conditions", "0004_get_condition_pixels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("plan", "0015_remove_scenario_max_budget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("max_budget", models.FloatField(null=True)),
                ("max_treatment_area_ratio", models.FloatField(null=True)),
                ("max_road_distance", models.FloatField(null=True)),
                ("max_slope", models.FloatField(null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RankedProjectArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField()),
                ("score", models.FloatField()),
                (
                    "project_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan.projectarea",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.scenario"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfigPriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conditions.condition",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.config"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="config",
            name="priorities",
            field=models.ManyToManyField(
                through="plan.ConfigPriority", to="conditions.condition"
            ),
        ),
        migrations.AddField(
            model_name="scenarioweightedpriority",
            name="weighted_priority",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="plan.configpriority",
            ),
        ),
    ]
