# Generated by Django 4.1.3 on 2023-03-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conditions', '0004_get_condition_pixels'),
        ('plan', '0016_config_rankedprojectarea_configpriority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectarea',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='scenarioweightedpriority',
            name='weighted_priority',
        ),
        migrations.AddField(
            model_name='scenario',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Processing'), (2, 'Processed'), (3, 'Failed')], default=0),
        ),
        migrations.AlterField(
            model_name='configpriority',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priorities',
            field=models.ManyToManyField(through='plan.ConfigPriority', to='conditions.condition'),
        ),
        migrations.AlterField(
            model_name='scenarioweightedpriority',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.configpriority'),
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
