# Generated by Django 4.1.3 on 2023-03-02 00:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0016_remove_projectarea_scenario_scenario_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="priorities",
        ),
    ]
