# Generated by Django 4.1.3 on 2023-03-06 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0016_scenario_favorited"),
        ("plan", "0018_remove_project_priorities_new_project_priorities"),
    ]

    operations = []
