version: '3.8'

services:
  backend:
    build: ./planscape
    image: planscape/backend
    volumes:
      - ./planscape/:/usr/src/planscape/
      - ./socket:/var/run/planscape
    # Expose port 5432 to get access to the PostGIS database
    expose:
      - 5432
    environment:
      - PLANSCAPE_DATABASE_HOST=host.docker.internal
      - PLANSCAPE_CORS_ALLOWED_HOSTS='http://127.0.0.1'
      - PLANSCAPE_CORS_ALLOWED_ORIGINS='http://127.0.0.1'
    depends_on:
      - frontend

  frontend:
    build: ./interface
    image: planscape/frontend
    volumes:
      - ./interface/:/usr/src/interface/
      - ./socket:/var/run/planscape
    ports:
      - 80:80

# Shared volume; used to set up communication by sockets from
# nginx -> uwsgi -> Django.
volumes:
  socket:
