name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/interface

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: src/interface/.node-version
          cache: 'npm'
          cache-dependency-path: src/interface/package-lock.json
      - run: npm ci
      - run: npm run lint

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/interface

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: src/interface/.node-version
          cache: 'npm'
          cache-dependency-path: src/interface/package-lock.json
      - run: npm ci
      - run: npm run test:prod

  storybook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/interface

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: src/interface/.node-version
          cache: 'npm'
          cache-dependency-path: src/interface/package-lock.json
      - run: npm ci
      - run: npm run build-storybook
