import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0028_dataset_style_datalayer_workspace"),
        ("funding_report", "0002_fundingopportunityreport_results"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundingopportunityreport",
            name="treatment_datalayer",
            field=models.ForeignKey(
                blank=True,
                help_text="DataLayer generated by clipping the treatments raster to this scenario's project areas.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funding_opportunity_reports",
                to="datasets.datalayer",
            ),
        ),
    ]
